name: bCoolDown
main: com.beecub.bCoolDown.bCoolDown
version: 1.1.0
author: beecub
description: >
             Shortcuts
commands:
  bCoolDown:
    description: Reload Command for bCoolDown
    usage: |
           /<command> [reload]